/* LIBGIMP - The GIMP Library
 * Copyright (C) 1995-2003 Peter Mattis and Spencer Kimball
 *
 * gimpcurve_pdb.c
 *
 * This library is free software: you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library.  If not, see
 * <https://www.gnu.org/licenses/>.
 */

/* NOTE: This file is auto-generated by pdbgen.pl */

#include "config.h"

#include "stamp-pdbgen.h"

#include "gimp.h"


/**
 * SECTION: gimpcurve
 * @title: gimpcurve
 * @short_description: Functions for manipulating curves.
 *
 * Functions for manipulating curves.
 **/


/**
 * gimp_curve_new:
 * @name: The curve name.
 *
 * Create a new curve.
 *
 * This procedure creates a new curve with the specified @name.
 *
 * Returns: (transfer none): The newly created curve.
 **/
GimpCurve *
gimp_curve_new (const gchar *name)
{
  GimpValueArray *args;
  GimpValueArray *return_vals;
  GimpCurve *curve = NULL;

  args = gimp_value_array_new_from_types (NULL,
                                          G_TYPE_STRING, name,
                                          G_TYPE_NONE);

  return_vals = _gimp_pdb_run_procedure_array (gimp_get_pdb (),
                                               "gimp-curve-new",
                                               args);
  gimp_value_array_unref (args);

  if (GIMP_VALUES_GET_ENUM (return_vals, 0) == GIMP_PDB_SUCCESS)
    curve = GIMP_VALUES_GET_CURVE (return_vals, 1);

  gimp_value_array_unref (return_vals);

  return curve;
}

/**
 * gimp_curve_get_n_points:
 * @curve: The curve.
 *
 * Returns the number of points in the curve.
 *
 * This procedure returns the number of points in the GimpCurve.
 *
 * Returns: The number of points in the curve.
 *
 * Since: 3.2
 **/
gint
gimp_curve_get_n_points (GimpCurve *curve)
{
  GimpValueArray *args;
  GimpValueArray *return_vals;
  gint n_points = 0;

  args = gimp_value_array_new_from_types (NULL,
                                          GIMP_TYPE_CURVE, curve,
                                          G_TYPE_NONE);

  return_vals = _gimp_pdb_run_procedure_array (gimp_get_pdb (),
                                               "gimp-curve-get-n-points",
                                               args);
  gimp_value_array_unref (args);

  if (GIMP_VALUES_GET_ENUM (return_vals, 0) == GIMP_PDB_SUCCESS)
    n_points = GIMP_VALUES_GET_INT (return_vals, 1);

  gimp_value_array_unref (return_vals);

  return n_points;
}

/**
 * gimp_curve_set_n_samples:
 * @curve: The curve.
 * @n_samples: The number of samples in the curve.
 *
 * Sets the number of samples in the curve
 *
 * This procedure sets the number of samples in the curve.
 *
 * Returns: TRUE on success.
 *
 * Since: 3.2
 **/
gboolean
gimp_curve_set_n_samples (GimpCurve *curve,
                          gint       n_samples)
{
  GimpValueArray *args;
  GimpValueArray *return_vals;
  gboolean success = TRUE;

  args = gimp_value_array_new_from_types (NULL,
                                          GIMP_TYPE_CURVE, curve,
                                          G_TYPE_INT, n_samples,
                                          G_TYPE_NONE);

  return_vals = _gimp_pdb_run_procedure_array (gimp_get_pdb (),
                                               "gimp-curve-set-n-samples",
                                               args);
  gimp_value_array_unref (args);

  success = GIMP_VALUES_GET_ENUM (return_vals, 0) == GIMP_PDB_SUCCESS;

  gimp_value_array_unref (return_vals);

  return success;
}

/**
 * gimp_curve_get_n_samples:
 * @curve: The curve.
 *
 * Returns the number of samples in the curve.
 *
 * This procedure returns the number of samples in the GimpCurve.
 *
 * Returns: The number of samples in the curve.
 *
 * Since: 3.2
 **/
gint
gimp_curve_get_n_samples (GimpCurve *curve)
{
  GimpValueArray *args;
  GimpValueArray *return_vals;
  gint n_samples = 0;

  args = gimp_value_array_new_from_types (NULL,
                                          GIMP_TYPE_CURVE, curve,
                                          G_TYPE_NONE);

  return_vals = _gimp_pdb_run_procedure_array (gimp_get_pdb (),
                                               "gimp-curve-get-n-samples",
                                               args);
  gimp_value_array_unref (args);

  if (GIMP_VALUES_GET_ENUM (return_vals, 0) == GIMP_PDB_SUCCESS)
    n_samples = GIMP_VALUES_GET_INT (return_vals, 1);

  gimp_value_array_unref (return_vals);

  return n_samples;
}

/**
 * gimp_curve_add_point:
 * @curve: The curve.
 * @x: X coordinate on the curve.
 * @y: Y coordinate on the curve.
 *
 * Add a point to the curve
 *
 * This procedure adds a point to the curve.
 *
 * Returns: Point ID.
 *
 * Since: 3.2
 **/
gint
gimp_curve_add_point (GimpCurve *curve,
                      gdouble    x,
                      gdouble    y)
{
  GimpValueArray *args;
  GimpValueArray *return_vals;
  gint point = 0;

  args = gimp_value_array_new_from_types (NULL,
                                          GIMP_TYPE_CURVE, curve,
                                          G_TYPE_DOUBLE, x,
                                          G_TYPE_DOUBLE, y,
                                          G_TYPE_NONE);

  return_vals = _gimp_pdb_run_procedure_array (gimp_get_pdb (),
                                               "gimp-curve-add-point",
                                               args);
  gimp_value_array_unref (args);

  if (GIMP_VALUES_GET_ENUM (return_vals, 0) == GIMP_PDB_SUCCESS)
    point = GIMP_VALUES_GET_INT (return_vals, 1);

  gimp_value_array_unref (return_vals);

  return point;
}

/**
 * gimp_curve_delete_point:
 * @curve: The curve.
 * @point: Point ID.
 *
 * Remove a point from the curve
 *
 * This procedure removes a point from the curve.
 *
 * Returns: TRUE on success.
 *
 * Since: 3.2
 **/
gboolean
gimp_curve_delete_point (GimpCurve *curve,
                         gint       point)
{
  GimpValueArray *args;
  GimpValueArray *return_vals;
  gboolean success = TRUE;

  args = gimp_value_array_new_from_types (NULL,
                                          GIMP_TYPE_CURVE, curve,
                                          G_TYPE_INT, point,
                                          G_TYPE_NONE);

  return_vals = _gimp_pdb_run_procedure_array (gimp_get_pdb (),
                                               "gimp-curve-delete-point",
                                               args);
  gimp_value_array_unref (args);

  success = GIMP_VALUES_GET_ENUM (return_vals, 0) == GIMP_PDB_SUCCESS;

  gimp_value_array_unref (return_vals);

  return success;
}

/**
 * gimp_curve_set_point:
 * @curve: The curve.
 * @point: Point ID.
 * @x: X coordinate on the curve.
 * @y: Y coordinate on the curve.
 *
 * Update the position of a point on the curve
 *
 * This procedure updates the position of a point on the curve.
 *
 * Returns: TRUE on success.
 *
 * Since: 3.2
 **/
gboolean
gimp_curve_set_point (GimpCurve *curve,
                      gint       point,
                      gdouble    x,
                      gdouble    y)
{
  GimpValueArray *args;
  GimpValueArray *return_vals;
  gboolean success = TRUE;

  args = gimp_value_array_new_from_types (NULL,
                                          GIMP_TYPE_CURVE, curve,
                                          G_TYPE_INT, point,
                                          G_TYPE_DOUBLE, x,
                                          G_TYPE_DOUBLE, y,
                                          G_TYPE_NONE);

  return_vals = _gimp_pdb_run_procedure_array (gimp_get_pdb (),
                                               "gimp-curve-set-point",
                                               args);
  gimp_value_array_unref (args);

  success = GIMP_VALUES_GET_ENUM (return_vals, 0) == GIMP_PDB_SUCCESS;

  gimp_value_array_unref (return_vals);

  return success;
}

/**
 * gimp_curve_clear_points:
 * @curve: The curve.
 *
 * Removes all points set in the curve
 *
 * This procedure removes all points set in the curve.
 *
 * Returns: TRUE on success.
 *
 * Since: 3.2
 **/
gboolean
gimp_curve_clear_points (GimpCurve *curve)
{
  GimpValueArray *args;
  GimpValueArray *return_vals;
  gboolean success = TRUE;

  args = gimp_value_array_new_from_types (NULL,
                                          GIMP_TYPE_CURVE, curve,
                                          G_TYPE_NONE);

  return_vals = _gimp_pdb_run_procedure_array (gimp_get_pdb (),
                                               "gimp-curve-clear-points",
                                               args);
  gimp_value_array_unref (args);

  success = GIMP_VALUES_GET_ENUM (return_vals, 0) == GIMP_PDB_SUCCESS;

  gimp_value_array_unref (return_vals);

  return success;
}

/**
 * gimp_curve_is_identity:
 * @curve: The curve.
 *
 * Returns where the curve is an identity curve.
 *
 * This procedure returns where the curve is an identity curve.
 *
 * Returns: Whether the curve is an identity curve.
 *
 * Since: 3.2
 **/
gboolean
gimp_curve_is_identity (GimpCurve *curve)
{
  GimpValueArray *args;
  GimpValueArray *return_vals;
  gboolean is_identity = FALSE;

  args = gimp_value_array_new_from_types (NULL,
                                          GIMP_TYPE_CURVE, curve,
                                          G_TYPE_NONE);

  return_vals = _gimp_pdb_run_procedure_array (gimp_get_pdb (),
                                               "gimp-curve-is-identity",
                                               args);
  gimp_value_array_unref (args);

  if (GIMP_VALUES_GET_ENUM (return_vals, 0) == GIMP_PDB_SUCCESS)
    is_identity = GIMP_VALUES_GET_BOOLEAN (return_vals, 1);

  gimp_value_array_unref (return_vals);

  return is_identity;
}
