/* LIBGIMP - The GIMP Library
 * Copyright (C) 1995-2003 Peter Mattis and Spencer Kimball
 *
 * gimpcurve_pdb.h
 *
 * This library is free software: you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library.  If not, see
 * <https://www.gnu.org/licenses/>.
 */

/* NOTE: This file is auto-generated by pdbgen.pl */

#if !defined (__GIMP_H_INSIDE__) && !defined (GIMP_COMPILATION)
#error "Only <libgimp/gimp.h> can be included directly."
#endif

#ifndef __GIMP_CURVE_PDB_H__
#define __GIMP_CURVE_PDB_H__

G_BEGIN_DECLS

/* For information look into the C source or the html documentation */


GimpCurve* gimp_curve_new           (const gchar *name);
gint       gimp_curve_get_n_points  (GimpCurve   *curve);
gboolean   gimp_curve_set_n_samples (GimpCurve   *curve,
                                     gint         n_samples);
gint       gimp_curve_get_n_samples (GimpCurve   *curve);
gint       gimp_curve_add_point     (GimpCurve   *curve,
                                     gdouble      x,
                                     gdouble      y);
gboolean   gimp_curve_delete_point  (GimpCurve   *curve,
                                     gint         point);
gboolean   gimp_curve_set_point     (GimpCurve   *curve,
                                     gint         point,
                                     gdouble      x,
                                     gdouble      y);
gboolean   gimp_curve_clear_points  (GimpCurve   *curve);
gboolean   gimp_curve_is_identity   (GimpCurve   *curve);


G_END_DECLS

#endif /* __GIMP_CURVE_PDB_H__ */
