/* GIMP - The GNU Image Manipulation Program
 * Copyright (C) 1995-2003 Spencer Kimball and Peter Mattis
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/* NOTE: This file is auto-generated by pdbgen.pl. */

#include "config.h"

#include "stamp-pdbgen.h"

#include <gegl.h>

#include <gdk-pixbuf/gdk-pixbuf.h>

#include "libgimpbase/gimpbase.h"

#include "libgimpbase/gimpbase.h"

#include "pdb-types.h"

#include "core/gimpcurve.h"
#include "core/gimpparamspecs.h"

#include "gimppdb.h"
#include "gimpprocedure.h"
#include "internal-procs.h"


static GimpValueArray *
curve_new_invoker (GimpProcedure         *procedure,
                   Gimp                  *gimp,
                   GimpContext           *context,
                   GimpProgress          *progress,
                   const GimpValueArray  *args,
                   GError               **error)
{
  gboolean success = TRUE;
  GimpValueArray *return_vals;
  const gchar *name;
  GimpCurve *curve = NULL;

  name = g_value_get_string (gimp_value_array_index (args, 0));

  if (success)
    {
      curve = (GimpCurve *) gimp_curve_new (name);

      if (! curve)
        success = FALSE;
    }

  return_vals = gimp_procedure_get_return_values (procedure, success,
                                                  error ? *error : NULL);

  if (success)
    g_value_set_object (gimp_value_array_index (return_vals, 1), curve);

  return return_vals;
}

static GimpValueArray *
curve_get_n_points_invoker (GimpProcedure         *procedure,
                            Gimp                  *gimp,
                            GimpContext           *context,
                            GimpProgress          *progress,
                            const GimpValueArray  *args,
                            GError               **error)
{
  gboolean success = TRUE;
  GimpValueArray *return_vals;
  GimpCurve *curve;
  gint n_points = 0;

  curve = g_value_get_object (gimp_value_array_index (args, 0));

  if (success)
    {
      n_points = gimp_curve_get_n_points (curve);
    }

  return_vals = gimp_procedure_get_return_values (procedure, success,
                                                  error ? *error : NULL);

  if (success)
    g_value_set_int (gimp_value_array_index (return_vals, 1), n_points);

  return return_vals;
}

static GimpValueArray *
curve_set_n_samples_invoker (GimpProcedure         *procedure,
                             Gimp                  *gimp,
                             GimpContext           *context,
                             GimpProgress          *progress,
                             const GimpValueArray  *args,
                             GError               **error)
{
  gboolean success = TRUE;
  GimpCurve *curve;
  gint n_samples;

  curve = g_value_get_object (gimp_value_array_index (args, 0));
  n_samples = g_value_get_int (gimp_value_array_index (args, 1));

  if (success)
    {
      gimp_curve_set_n_samples (curve, n_samples);
    }

  return gimp_procedure_get_return_values (procedure, success,
                                           error ? *error : NULL);
}

static GimpValueArray *
curve_get_n_samples_invoker (GimpProcedure         *procedure,
                             Gimp                  *gimp,
                             GimpContext           *context,
                             GimpProgress          *progress,
                             const GimpValueArray  *args,
                             GError               **error)
{
  gboolean success = TRUE;
  GimpValueArray *return_vals;
  GimpCurve *curve;
  gint n_samples = 0;

  curve = g_value_get_object (gimp_value_array_index (args, 0));

  if (success)
    {
      n_samples = gimp_curve_get_n_samples (curve);
    }

  return_vals = gimp_procedure_get_return_values (procedure, success,
                                                  error ? *error : NULL);

  if (success)
    g_value_set_int (gimp_value_array_index (return_vals, 1), n_samples);

  return return_vals;
}

static GimpValueArray *
curve_add_point_invoker (GimpProcedure         *procedure,
                         Gimp                  *gimp,
                         GimpContext           *context,
                         GimpProgress          *progress,
                         const GimpValueArray  *args,
                         GError               **error)
{
  gboolean success = TRUE;
  GimpValueArray *return_vals;
  GimpCurve *curve;
  gdouble x;
  gdouble y;
  gint point = 0;

  curve = g_value_get_object (gimp_value_array_index (args, 0));
  x = g_value_get_double (gimp_value_array_index (args, 1));
  y = g_value_get_double (gimp_value_array_index (args, 2));

  if (success)
    {
      point = gimp_curve_add_point (curve, x, y);

      if (point < 0)
        success = FALSE;
    }

  return_vals = gimp_procedure_get_return_values (procedure, success,
                                                  error ? *error : NULL);

  if (success)
    g_value_set_int (gimp_value_array_index (return_vals, 1), point);

  return return_vals;
}

static GimpValueArray *
curve_delete_point_invoker (GimpProcedure         *procedure,
                            Gimp                  *gimp,
                            GimpContext           *context,
                            GimpProgress          *progress,
                            const GimpValueArray  *args,
                            GError               **error)
{
  gboolean success = TRUE;
  GimpCurve *curve;
  gint point;

  curve = g_value_get_object (gimp_value_array_index (args, 0));
  point = g_value_get_int (gimp_value_array_index (args, 1));

  if (success)
    {
      gimp_curve_delete_point (curve, point);
    }

  return gimp_procedure_get_return_values (procedure, success,
                                           error ? *error : NULL);
}

static GimpValueArray *
curve_set_point_invoker (GimpProcedure         *procedure,
                         Gimp                  *gimp,
                         GimpContext           *context,
                         GimpProgress          *progress,
                         const GimpValueArray  *args,
                         GError               **error)
{
  gboolean success = TRUE;
  GimpCurve *curve;
  gint point;
  gdouble x;
  gdouble y;

  curve = g_value_get_object (gimp_value_array_index (args, 0));
  point = g_value_get_int (gimp_value_array_index (args, 1));
  x = g_value_get_double (gimp_value_array_index (args, 2));
  y = g_value_get_double (gimp_value_array_index (args, 3));

  if (success)
    {
      gimp_curve_set_point (curve, point, x, y);
    }

  return gimp_procedure_get_return_values (procedure, success,
                                           error ? *error : NULL);
}

static GimpValueArray *
curve_clear_points_invoker (GimpProcedure         *procedure,
                            Gimp                  *gimp,
                            GimpContext           *context,
                            GimpProgress          *progress,
                            const GimpValueArray  *args,
                            GError               **error)
{
  gboolean success = TRUE;
  GimpCurve *curve;

  curve = g_value_get_object (gimp_value_array_index (args, 0));

  if (success)
    {
      gimp_curve_clear_points (curve);
    }

  return gimp_procedure_get_return_values (procedure, success,
                                           error ? *error : NULL);
}

static GimpValueArray *
curve_is_identity_invoker (GimpProcedure         *procedure,
                           Gimp                  *gimp,
                           GimpContext           *context,
                           GimpProgress          *progress,
                           const GimpValueArray  *args,
                           GError               **error)
{
  gboolean success = TRUE;
  GimpValueArray *return_vals;
  GimpCurve *curve;
  gboolean is_identity = FALSE;

  curve = g_value_get_object (gimp_value_array_index (args, 0));

  if (success)
    {
      is_identity = gimp_curve_is_identity (curve);
    }

  return_vals = gimp_procedure_get_return_values (procedure, success,
                                                  error ? *error : NULL);

  if (success)
    g_value_set_boolean (gimp_value_array_index (return_vals, 1), is_identity);

  return return_vals;
}

void
register_curve_procs (GimpPDB *pdb)
{
  GimpProcedure *procedure;

  /*
   * gimp-curve-new
   */
  procedure = gimp_procedure_new (curve_new_invoker, FALSE);
  gimp_object_set_static_name (GIMP_OBJECT (procedure),
                               "gimp-curve-new");
  gimp_procedure_set_static_help (procedure,
                                  "Create a new curve.",
                                  "This procedure creates a new curve with the specified @name.",
                                  NULL);
  gimp_procedure_set_static_attribution (procedure,
                                         "Spencer Kimball & Peter Mattis",
                                         "Spencer Kimball & Peter Mattis",
                                         "1995-1996");
  gimp_procedure_add_argument (procedure,
                               gimp_param_spec_string ("name",
                                                       "name",
                                                       "The curve name",
                                                       FALSE, FALSE, FALSE,
                                                       NULL,
                                                       GIMP_PARAM_READWRITE));
  gimp_procedure_add_return_value (procedure,
                                   gimp_param_spec_curve ("curve",
                                                          "curve",
                                                          "The newly created curve",
                                                          FALSE,
                                                          GIMP_PARAM_READWRITE));
  gimp_pdb_register_procedure (pdb, procedure);
  g_object_unref (procedure);

  /*
   * gimp-curve-get-n-points
   */
  procedure = gimp_procedure_new (curve_get_n_points_invoker, FALSE);
  gimp_object_set_static_name (GIMP_OBJECT (procedure),
                               "gimp-curve-get-n-points");
  gimp_procedure_set_static_help (procedure,
                                  "Returns the number of points in the curve.",
                                  "This procedure returns the number of points in the GimpCurve.",
                                  NULL);
  gimp_procedure_set_static_attribution (procedure,
                                         "Alex S.",
                                         "Alex S.",
                                         "2026");
  gimp_procedure_add_argument (procedure,
                               gimp_param_spec_curve ("curve",
                                                      "curve",
                                                      "The curve",
                                                      FALSE,
                                                      GIMP_PARAM_READWRITE));
  gimp_procedure_add_return_value (procedure,
                                   g_param_spec_int ("n-points",
                                                     "n points",
                                                     "The number of points in the curve",
                                                     G_MININT32, G_MAXINT32, 0,
                                                     GIMP_PARAM_READWRITE));
  gimp_pdb_register_procedure (pdb, procedure);
  g_object_unref (procedure);

  /*
   * gimp-curve-set-n-samples
   */
  procedure = gimp_procedure_new (curve_set_n_samples_invoker, FALSE);
  gimp_object_set_static_name (GIMP_OBJECT (procedure),
                               "gimp-curve-set-n-samples");
  gimp_procedure_set_static_help (procedure,
                                  "Sets the number of samples in the curve",
                                  "This procedure sets the number of samples in the curve.",
                                  NULL);
  gimp_procedure_set_static_attribution (procedure,
                                         "Alex S.",
                                         "Alex S.",
                                         "2026");
  gimp_procedure_add_argument (procedure,
                               gimp_param_spec_curve ("curve",
                                                      "curve",
                                                      "The curve",
                                                      FALSE,
                                                      GIMP_PARAM_READWRITE));
  gimp_procedure_add_argument (procedure,
                               g_param_spec_int ("n-samples",
                                                 "n samples",
                                                 "The number of samples in the curve",
                                                 0, G_MAXINT32, 0,
                                                 GIMP_PARAM_READWRITE));
  gimp_pdb_register_procedure (pdb, procedure);
  g_object_unref (procedure);

  /*
   * gimp-curve-get-n-samples
   */
  procedure = gimp_procedure_new (curve_get_n_samples_invoker, FALSE);
  gimp_object_set_static_name (GIMP_OBJECT (procedure),
                               "gimp-curve-get-n-samples");
  gimp_procedure_set_static_help (procedure,
                                  "Returns the number of samples in the curve.",
                                  "This procedure returns the number of samples in the GimpCurve.",
                                  NULL);
  gimp_procedure_set_static_attribution (procedure,
                                         "Alex S.",
                                         "Alex S.",
                                         "2026");
  gimp_procedure_add_argument (procedure,
                               gimp_param_spec_curve ("curve",
                                                      "curve",
                                                      "The curve",
                                                      FALSE,
                                                      GIMP_PARAM_READWRITE));
  gimp_procedure_add_return_value (procedure,
                                   g_param_spec_int ("n-samples",
                                                     "n samples",
                                                     "The number of samples in the curve",
                                                     G_MININT32, G_MAXINT32, 0,
                                                     GIMP_PARAM_READWRITE));
  gimp_pdb_register_procedure (pdb, procedure);
  g_object_unref (procedure);

  /*
   * gimp-curve-add-point
   */
  procedure = gimp_procedure_new (curve_add_point_invoker, FALSE);
  gimp_object_set_static_name (GIMP_OBJECT (procedure),
                               "gimp-curve-add-point");
  gimp_procedure_set_static_help (procedure,
                                  "Add a point to the curve",
                                  "This procedure adds a point to the curve.",
                                  NULL);
  gimp_procedure_set_static_attribution (procedure,
                                         "Alex S.",
                                         "Alex S.",
                                         "2026");
  gimp_procedure_add_argument (procedure,
                               gimp_param_spec_curve ("curve",
                                                      "curve",
                                                      "The curve",
                                                      FALSE,
                                                      GIMP_PARAM_READWRITE));
  gimp_procedure_add_argument (procedure,
                               g_param_spec_double ("x",
                                                    "x",
                                                    "X coordinate on the curve",
                                                    -G_MAXDOUBLE, G_MAXDOUBLE, 0,
                                                    GIMP_PARAM_READWRITE));
  gimp_procedure_add_argument (procedure,
                               g_param_spec_double ("y",
                                                    "y",
                                                    "Y coordinate on the curve",
                                                    -G_MAXDOUBLE, G_MAXDOUBLE, 0,
                                                    GIMP_PARAM_READWRITE));
  gimp_procedure_add_return_value (procedure,
                                   g_param_spec_int ("point",
                                                     "point",
                                                     "Point ID",
                                                     G_MININT32, G_MAXINT32, 0,
                                                     GIMP_PARAM_READWRITE));
  gimp_pdb_register_procedure (pdb, procedure);
  g_object_unref (procedure);

  /*
   * gimp-curve-delete-point
   */
  procedure = gimp_procedure_new (curve_delete_point_invoker, FALSE);
  gimp_object_set_static_name (GIMP_OBJECT (procedure),
                               "gimp-curve-delete-point");
  gimp_procedure_set_static_help (procedure,
                                  "Remove a point from the curve",
                                  "This procedure removes a point from the curve.",
                                  NULL);
  gimp_procedure_set_static_attribution (procedure,
                                         "Alex S.",
                                         "Alex S.",
                                         "2026");
  gimp_procedure_add_argument (procedure,
                               gimp_param_spec_curve ("curve",
                                                      "curve",
                                                      "The curve",
                                                      FALSE,
                                                      GIMP_PARAM_READWRITE));
  gimp_procedure_add_argument (procedure,
                               g_param_spec_int ("point",
                                                 "point",
                                                 "Point ID",
                                                 0, G_MAXINT32, 0,
                                                 GIMP_PARAM_READWRITE));
  gimp_pdb_register_procedure (pdb, procedure);
  g_object_unref (procedure);

  /*
   * gimp-curve-set-point
   */
  procedure = gimp_procedure_new (curve_set_point_invoker, FALSE);
  gimp_object_set_static_name (GIMP_OBJECT (procedure),
                               "gimp-curve-set-point");
  gimp_procedure_set_static_help (procedure,
                                  "Update the position of a point on the curve",
                                  "This procedure updates the position of a point on the curve.",
                                  NULL);
  gimp_procedure_set_static_attribution (procedure,
                                         "Alex S.",
                                         "Alex S.",
                                         "2026");
  gimp_procedure_add_argument (procedure,
                               gimp_param_spec_curve ("curve",
                                                      "curve",
                                                      "The curve",
                                                      FALSE,
                                                      GIMP_PARAM_READWRITE));
  gimp_procedure_add_argument (procedure,
                               g_param_spec_int ("point",
                                                 "point",
                                                 "Point ID",
                                                 G_MININT32, G_MAXINT32, 0,
                                                 GIMP_PARAM_READWRITE));
  gimp_procedure_add_argument (procedure,
                               g_param_spec_double ("x",
                                                    "x",
                                                    "X coordinate on the curve",
                                                    -G_MAXDOUBLE, G_MAXDOUBLE, 0,
                                                    GIMP_PARAM_READWRITE));
  gimp_procedure_add_argument (procedure,
                               g_param_spec_double ("y",
                                                    "y",
                                                    "Y coordinate on the curve",
                                                    -G_MAXDOUBLE, G_MAXDOUBLE, 0,
                                                    GIMP_PARAM_READWRITE));
  gimp_pdb_register_procedure (pdb, procedure);
  g_object_unref (procedure);

  /*
   * gimp-curve-clear-points
   */
  procedure = gimp_procedure_new (curve_clear_points_invoker, FALSE);
  gimp_object_set_static_name (GIMP_OBJECT (procedure),
                               "gimp-curve-clear-points");
  gimp_procedure_set_static_help (procedure,
                                  "Removes all points set in the curve",
                                  "This procedure removes all points set in the curve.",
                                  NULL);
  gimp_procedure_set_static_attribution (procedure,
                                         "Alex S.",
                                         "Alex S.",
                                         "2026");
  gimp_procedure_add_argument (procedure,
                               gimp_param_spec_curve ("curve",
                                                      "curve",
                                                      "The curve",
                                                      FALSE,
                                                      GIMP_PARAM_READWRITE));
  gimp_pdb_register_procedure (pdb, procedure);
  g_object_unref (procedure);

  /*
   * gimp-curve-is-identity
   */
  procedure = gimp_procedure_new (curve_is_identity_invoker, FALSE);
  gimp_object_set_static_name (GIMP_OBJECT (procedure),
                               "gimp-curve-is-identity");
  gimp_procedure_set_static_help (procedure,
                                  "Returns where the curve is an identity curve.",
                                  "This procedure returns where the curve is an identity curve.",
                                  NULL);
  gimp_procedure_set_static_attribution (procedure,
                                         "Alex S.",
                                         "Alex S.",
                                         "2026");
  gimp_procedure_add_argument (procedure,
                               gimp_param_spec_curve ("curve",
                                                      "curve",
                                                      "The curve",
                                                      FALSE,
                                                      GIMP_PARAM_READWRITE));
  gimp_procedure_add_return_value (procedure,
                                   g_param_spec_boolean ("is-identity",
                                                         "is identity",
                                                         "Whether the curve is an identity curve.",
                                                         FALSE,
                                                         GIMP_PARAM_READWRITE));
  gimp_pdb_register_procedure (pdb, procedure);
  g_object_unref (procedure);
}
